#!/bin/bash
# Test 1. Wrong argument
./private f &> /dev/null || echo "Test 1: successful."

# Test 2. Install applications
if sudo ./private a &> /dev/null; then
    if [[ -z $(which shellcheck) ]]; then
        echo "Test 2: Error - Shellcheck could not be found."
        exit 1
    else
        echo "Test 2: successful."
    fi
else
    echo "Test 2: Fail."
    exit 1
fi

# Test 3. Install theme
if ./private t &> /dev/null; then
    if [[ ! -d "$HOME"/.themes ]]; then
        echo "Test 3: Error - Didn't create the .themes folder."
        exit 1
    else
        echo "Test 3: successful."
    fi
else
    echo "Test 3: Fail."
    exit 1
fi

# Test 4
# It should be impossible to install plugins with sudo
sudo ./private --plugins &> /dev/null
EXIT_CODE=$?
[[ "$EXIT_CODE" == 0 ]] && echo exit 1 

