#!/bin/bash
# Test 1. Wrong argument
./private -f || echo -e "Test 1: successful."

# Test 2. Install applications
if ./private -a; then
    if [[ -z $(which shellcheck) ]]; then
        echo "Test 2: Error - Shellcheck could not be found"
        exit 1
    else
        echo "Test 2: successful"
    fi
else
    echo "Test 2: Fail"
fi

# Test 3. Install yocto libraries
if ./private -y; then
    if [[ -z $(which python2) ]]; then
        echo "Test 3: Error - Python2 not found."
        exit 1
    else
        echo "Test 3: successful"
    fi
else
    echo "Test 3: Fail"
fi

# Test 4. Install theme
if ./private -t; then
    if [[ ! -d "$HOME"/.themes ]]; then
        echo "Test 4: Error - Didn't create the .themes folder"
        exit 1
    else
        echo "Test 4: successful"
    fi
else
    echo "Test 4: Fail"
fi
