name: stupid-ci-for-stupid-project 
run-name: ${{ github.actor }} is mastering actions. 
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'


