name: stupid-ci-for-stupid-project 
run-name: ${{ github.actor }} is mastering actions. 
on: 
  push:
    branches:
      - '*'
  pull_request: 
    branches:
      - main

jobs:
  running-some-code:
    runs-on: ubuntu-latest
    name: testing
    strategy:
      matrix:
        version: [5, 3]
    steps:
      - uses: actions/checkout@v3
      - run: ./test_script ${{ matrix.version }}


